### ISSUE TITLE
signing fails due to invalid hostname

### ISSUE THREAD

**Issue by thrillfall** [R0Wi/nextcloud-appstore-push-action#7]
I added your workflow (thanks!) but cannot sign and upload. 
https://github.com/thrillfall/nextcloud-gpodder/runs/3330166688?check_suite_focus=true

```
Run R0Wi/nextcloud-appstore-push-action@v1.0.3
  with:
    nightly: false
  env:
    APP_NAME: gpoddersync
    app_name: gpoddersync
    appstore_token: ***
    download_url: https://github.com/thrillfall/nextcloud-gpodder/releases/download/release-test-06/gpoddersync.tar.gz
    app_private_key: ***
    nightly: false
Downloading app tarball for signing
http://: Invalid host name.
Error: Process completed with exit code 1.
```
what am i doing wrong?

**Comment by R0Wi** [comment]
Hi @thrillfall, for me your workflow file looks just fine so i cannot see any error. Because of the log output i'd say the script can't download the app tarball given in the `download_url` parameter. Could you try to set this parameter manually to any valid url? Could be that there is a problem with the "attach to release" action just before this action here runs.

**Comment by thrillfall** [comment]
The URL in _download_url_ is valid. The tarball is added to the release assets

**Comment by thrillfall** [comment]
Where can i find the code that generates the "invalid hostname" error?

**Comment by thrillfall** [comment]
Passing the URL  from the previous steps seems to fail. I wonder where the wrong value "http://” originates?

**Comment by R0Wi** [comment]
Well that's indeed a good question 😄 Seems like the "attach to release" action generates a wrong output in `download_url: ${{ steps.attach_to_release.outputs.browser_download_url }}`. So might be worth raising a new issue at https://github.com/svenstaro/upload-release-action.

What you could check:
* Echo the mentioned variable in a separate step like `run: echo ownload_url: ${{ steps.attach_to_release.outputs.browser_download_url }}` 
* Instead of using the variable use a temporary hard coded url to see if that works

**Comment by thrillfall** [comment]
The "attach to release" action generates the download_url output just fine (meaning a valid url to the tarball). Hardcoding that url results in the same error.
https://github.com/thrillfall/nextcloud-gpodder/runs/3338924110?check_suite_focus=true

**Comment by thrillfall** [comment]
The environment variable is not set in the action. I forked this action and echoed the value of DOWNLOAD_URL and its empty:
https://github.com/thrillfall/nextcloud-gpodder/runs/3339083424?check_suite_focus=true

**Comment by R0Wi** [comment]
This is really strange since i use the action in the same version like you in two of my own projects
* https://github.com/nextcloud/files_photospheres/actions/runs/1020227013
* https://github.com/R0Wi/workflow_ocr/actions/runs/1056571882

I have to investigate further please give me some time for that.

**Comment by thrillfall** [comment]
Wild guess:   runs-on: ubuntu-latest

**Comment by R0Wi** [comment]
According to https://github.com/actions/virtual-environments this should be the same as Ubuntu 20 but you could try it 👍

**Comment by thrillfall** [comment]
Image change die not help.
But I found that none of the environment variables are being set

**Comment by R0Wi** [comment]
I did a quick test with some hardcoded values https://github.com/R0Wi/github-action-testrepo/runs/3343668776?check_suite_focus=true

Like you can see the download is successful (of course the app tarball signing step fails but the script came over the first step where it downloads the app tarball). So to be honest currently i don't have any idea and i'm not able to reproduce the issue unfortumately :cry:

**Comment by R0Wi** [comment]
Oh i might have found the culprit... you're using
```yaml
    env: ...
```
but it has to be
```yaml
    with: ...
```

Just noticed that it's wrong in the docs and examples. Will fix that ASAP
